extendido = {

             'ADCA':'B9',
             'ADCB':'F9',
             'ADDA':'BB',
             'ADDB':'FB',
             'ADDD':'F3',
             'ANDA':'B4',
             'ANDB':'F4',
             'ASL':'78',
             'ASR':'77',
             'BITA':'B5',
             'BITB':'F5',
             'CLR':'7F',
             'CMPA':'B1',
             'CMPB':'F1',
             'COM':'73',
             'CPD':'1AB3',
             'CPX':'BC',
             'CPY':'18BC',
             'DEC':'7A',
             'EORA':'B8',
             'EORB':'F8',
             'INC':'7C',
             'JMP':'7E',
             'JSR':'BD',
             'LDAA':'B6',
             'LDAB':'F6',
             'LDD':'FC',
             'LDS':'BE',
             'LDX':'FE',
             'LDY':'18FE',
             'LSL':'78',
             'LSR':'74',
             'NEG':'70',
             'ORAA':'BA',
             'ORAB':'FA',
             'ROL':'79',
             'ROR':'76',
             'SBCA':'B2',
             'SBCB':'F2',
             'STAA':'B7',
             'STAB':'F7',
             'STD':'FD',
             'STS':'BF',
             'STX':'FF',
             'STY':'FF',
             'SUBA':'B0',
             'SUBB':'F0',
             'SUBD':'B3',
             'TST':'7D',

             }





inmediato = {

             'ADCA':'89',
             'ADCB':'C9',
             'ADDA':'8B',
             'ADDB':'CB',
             'ADDD':'C3',
             'ANDA':'84',
             'ANDB':'C4',
             'BITA':'85',
             'BITB':'C5',
             'CMPA':'81',
             'CMPB':'C1',
             'CPD':'1A83',
             'CPX':'8C',
             'CPY':'188C',
             'EORA':'88',
             'EORB':'C8',
             'LDAA':'86',
             'LDAB':'C6',
             'LDD':'CC',
             'LDS':'8E',
             'LDX':'CE',
             'LDY':'18CE',
             'ORAA':'8A',
             'ORAB':'CA',
             'SBCA':'82',
             'SBCB':'C2',
             'SUBA':'80',
             'SUBB':'C0',
             'SUBD':'83',

             }




indexadox = {

             'ADCA':'A9',
             'ADCB':'E9',
             'ADDA':'AB',
             'ADDB':'EB',
             'ADDD':'E3',
             'ANDA':'B4',
             'ANDB':'E4',
             'ASL':'68',
             'ASR':'67',
             'BITA':'A5',
             'BITB':'E5',
             'CLR':'6F',
             'CMPA':'A1',
             'CMPB':'E1',
             'COM':'63',
             'CPD':'1AA3',
             'CPX':'AC',
             'CPY':'1AAC',
             'DEC':'6A',
             'EORA':'A8',
             'EORB':'E8',
             'INC':'6C',
             'JMP':'6E',
             'JSR':'AD',
             'LDAA':'A6',
             'LDAB':'E6',
             'LDD':'EC',
             'LDS':'AE',
             'LDX':'EE',
             'LDY':'1AEE',
             'LSL':'68',
             'LSR':'64',
             'NEG':'60',
             'ORAA':'AA',
             'ORAB':'EA',
             'ROL':'69',
             'ROR':'66',
             'SBCA':'A2',
             'SBCB':'E2',
             'STAA':'A7',
             'STAB':'E7',
             'STD':'ED',
             'STS':'AF',
             'STX':'EF',
             'STY':'1AEF',
             'SUBA':'A0',
             'SUBB':'E0',
             'SUBD':'A3',
             'TST':'6D',

             }





indexadoy = {

             'ADCA':'18A9',
             'ADCB':'18E9',
             'ADDA':'18AB',
             'ADDB':'18EB',
             'ADDD':'18E3',
             'ANDA':'18A4',
             'ANDB':'18E4',
             'ASL':'1868',
             'ASR':'1867',
             'BITA':'18A5',
             'BITB':'18E5',
             'CLR':'186F',
             'CMPA':'18A1',
             'CMPB':'18E1',
             'COM':'1863',
             'CPD':'CDA3',
             'CPX':'CDAC',
             'CPY':'18AC',
             'DEC':'186A',
             'EORA':'18A8',
             'EORB':'18E8',
             'INC':'186C',
             'JMP':'186E',
             'JSR':'18AD',
             'LDAA':'18A6',
             'LDAB':'18E6',
             'LDD':'18EC',
             'LDS':'18AE',
             'LDX':'CDEE',
             'LDY':'18EE',
             'LSL':'1868',
             'LSR':'1864',
             'NEG':'1860',
             'ORAA':'18AA',
             'ORAB':'18EA',
             'ROL':'1869',
             'ROR':'1866',
             'SBCA':'18A2',
             'SBCB':'18E2',
             'STAA':'18A7',
             'STAB':'18E7',
             'STD':'18ED',
             'STS':'18AF',
             'STX':'CDEF',
             'STY':'18EF',
             'SUBA':'18A0',
             'SUBB':'18E0',
             'SUBD':'18A3',
             'TST':'186D',

             }



directo   = {

             'ADCA':'99',
             'ADCB':'D9',
             'ADDA':'9B',
             'ADDB':'DB',
             'ADDD':'D3',
             'ANDA':'94',
             'ANDB':'D4',
             'BITA':'95',
             'BITB':'D5',
             'CMPA':'91',
             'CMPB':'D1',
             'CPD':'1A93',
             'CPX':'9C',
             'CPY':'189C',
             'EORA':'98',
             'EORB':'D8',
             'JSR':'9D',
             'LDAA':'96',
             'LDAB':'D6',
             'LDD':'DC',
             'LDS':'9E',
             'LDX':'DE',
             'LDY':'18DE',
             'ORAA':'9A',
             'ORAB':'DA',
             'SBCA':'92',
             'SBCB':'D2',
             'STAA':'97',
             'STAB':'D7',
             'STD':'DD',
             'STS':'9F',
             'STX':'DF',
             'STY':'18DF',
             'SUBA':'90',
             'SUBB':'D0',
             'SUBD':'93',

             }


inherente = {

             'ABA':'1B',
             'ABX':'3A',
             'ABY':'183A',
             'ASLA':'48',
             'ASLB':'58',
             'ASLD':'5',
             'ASRA':'47',
             'ASRB':'57',
             'CBA':'11',
             'CLC':'0C',
             'CLI':'0E',
             'CLRA':'4F',
             'CLRB':'5F',
             'CLV':'0A',
             'COMA':'43',
             'COMB':'53',
             'DAA':'19',
             'DECA':'4A',
             'DECB':'5A',
             'DES':'34',
             'DEX':'09',
             'DEY':'1809',
             'FDIV':'03',
             'IDIV':'02',
             'INCA':'4C',
             'INCB':'5C',
             'INS':'31',
             'INX':'08',
             'INY':'1808',
             'LSLA':'48',
             'LSLB':'58',
             'LSLD':'05',
             'LSRA':'44',
             'LSRB':'54',
             'LSRD':'04',
             'MUL':'3D',
             'NEGA':'40',
             'NEGB':'50',
             'NOP':'01',
             'PSHA':'36',
             'PSHB':'37',
             'PSHX':'3C',
             'PSHY':'183C',
             'PULA':'32',
             'PULB':'33',
             'PULX':'38',
             'PULY':'1838',
             'ROLA':'49',
             'ROLB':'59',
             'RORA':'46',
             'RORB':'56',
             'RTI':'3B',
             'RTS':'39',
             'SBA':'10',
             'SEC':'OD',
             'SEI':'OF',
             'SEV':'OB',
             'STOP':'CF',
             'SWI':'3F',
             'TAB':'16',
             'TAP':'06',
             'TBA':'17',
             'TETS':'00',
             'TPA':'07',
             'TSTA':'4D',
             'TSTB':'5D',
             'TSX':'30',
             'TSY':'1830',
             'TXS':'35',
             'TYS':'1835',
             'WAI':'3E',
             'XGDX':'8F',
             'XGDY':'188F',

             }




relativo  = {

             'BCC':'24',
             'BCS':'25',
             'BEQ':'27',
             'BGE':'2C',
             'BGT':'2E',
             'BHI':'22',
             'BHS':'24',
             'BLE':'2F',
             'BLO':'25',
             'BLS':'23',
             'BLT':'2D',
             'BMI':'2B',
             'BNE':'26',
             'BPL':'2A',
             'BRA':'20',
             'BRN':'21',
             'BSR':'8D',
             'BVC':'28',
             'BVS':'29',

             }

especiales = {

              'BCLR':['15','1D','181D'],
              'BRCLR':['13','1F','181F'],
              'BRSET':['12','1E','181E'],
              'BSET':['14','1C','181C'],

              }